# Generated by Django 3.2.5 on 2021-11-23 12:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('firehome', '0003_flame_author'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Flame',
            new_name='Post',
        ),
    ]
